---
- name: installation vm local environnement CI
  hosts: all
  tasks: 
    - name: ensure dev-packages present
      package: 
        name:
         - htop
         - cmake
         - g++-10
         - libboost-all-dev
         - libfmt-dev
         - libspdlog-dev
         - libyaml-cpp-dev
        state: present
      become: yes
      become_user: root
      

    - name: git clone https://github.com/padget/blackci
      git: 
        repo: https://github.com/padget/blackci
        dest: /home/vagrant/blackci

    - name: 'git configuration user.email and user.name'
      git_config:
        repo: /home/vagrant/blackci
        scope: local
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      with_items: 
        - name: user.email 
          value: 'padget.pro@gmail.com'
        - name: user.name 
          value: 'padget'
